// Code generated by MockGen. DO NOT EDIT.
// Source: coding-challenge-go/pkg/api/seller/v1 (interfaces: Repository)

// Package v1 is a generated GoMock package.
package v1

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// FindByUUID mocks base method.
func (m *MockRepository) FindByUUID(arg0 string) (*Seller, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUUID", arg0)
	ret0, _ := ret[0].(*Seller)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUUID indicates an expected call of FindByUUID.
func (mr *MockRepositoryMockRecorder) FindByUUID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUUID", reflect.TypeOf((*MockRepository)(nil).FindByUUID), arg0)
}

// list mocks base method.
func (m *MockRepository) list() ([]*Seller, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "list")
	ret0, _ := ret[0].([]*Seller)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// list indicates an expected call of list.
func (mr *MockRepositoryMockRecorder) list() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "list", reflect.TypeOf((*MockRepository)(nil).list))
}
