// Code generated by MockGen. DO NOT EDIT.
// Source: coding-challenge-go/pkg/api/seller/v2 (interfaces: Repository)

// Package v2 is a generated GoMock package.
package v2

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// getTopSellers mocks base method.
func (m *MockRepository) getTopSellers(arg0 int) ([]*Seller, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getTopSellers", arg0)
	ret0, _ := ret[0].([]*Seller)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getTopSellers indicates an expected call of getTopSellers.
func (mr *MockRepositoryMockRecorder) getTopSellers(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getTopSellers", reflect.TypeOf((*MockRepository)(nil).getTopSellers), arg0)
}
